### ISSUE TITLE
Cake.Issues.MsBuild StructuredLogger 2.2.206

### ISSUE THREAD

**Issue by romerod** [cake-contrib/Cake.Issues#444]
Since we are building our application with VS 17.9.x we have an ArgumentNullException when reading the issues from the binary log:

Using version 2.2.206 of the StructuredLogger fixes this issue and I saw that you are already using that.

When will you publish a new version of the nuget package?

Thanks for your great work.

StackTrace:

`
Error: System.ArgumentNullException: Value cannot be null. (Parameter 'format')
     at System.ArgumentNullException.Throw(String paramName)
     at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan``1 args)
     at System.String.Format(String format, Object[] args)
     at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.FormatResourceStringIgnoreCodeAndKeyword(String resource, String[] arguments) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.Viewer.cs:line 175
     at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.GetPropertyReassignmentMessage(String propertyName, String newValue, String previousValue, String location) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.Viewer.cs:line 72
     at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.ReadPropertyReassignmentEventArgs() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.cs:line 1096
     at Microsoft.Build.Logging.StructuredLogger.BuildEventArgsReader.Read() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BuildEventArgsReader.cs:line 194
     at Microsoft.Build.Logging.StructuredLogger.BinLogReader.ReadRecordsFromDecompressedStream(Stream decompressedStream)+MoveNext() in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 327
     at System.Linq.Enumerable.SelectEnumerableIterator``2.MoveNext()
     at Cake.Issues.MsBuild.LogFileFormat.BinaryLogFileFormat.ReadIssues(MsBuildIssuesProvider issueProvider, IRepositorySettings repositorySettings, MsBuildIssuesSettings issueProviderSettings) in /_/src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs:line 29
`

**Comment by pascalberger** [comment]
Yes, Visual Studio 17.9 comes with a new bin log format which is not yet supported. 

Note that you can also use the logger shipped with Cake.Issues.MsBuild instead of the default binary logger shipped with Visual Studio if you want to ensure to always use a compatible version:

```
var msBuildSettings = 
    new DotNetCoreMSBuildSettings()
        .WithLogger(
            "BinaryLogger," + Tools.Resolve("Cake.Issues.MsBuild*/**/StructuredLogger.dll"),
            "",
            YouBinLogOutputPath);

DotNetCoreBuild(
    YouSlnPath, 
    new DotNetCoreBuildSettings
    {
        MSBuildSettings = msBuildSettings
    });
```

I'm creating a release as we speak.

**Comment by pascalberger** [comment]
@romerod [Version 4.1.0](https://github.com/cake-contrib/Cake.Issues/releases/tag/4.1.0) with support for binlog version 17 format has been released
